graphhopper:
  # ローカルファイルパス（S3からダウンロード後）
  datareader.file: /graphhopper/data/map.osm.pbf
  
  # グラフキャッシュの保存場所
  graph.location: /graphhopper/graph-cache
  
  # インポート設定
  import.osm.ignored_highways: ""
  
  # 標高データを無効化（処理時間短縮）
  graph.elevation.provider: ""
  
  # メモリマップアクセス（大規模データ対応）
  graph.dataaccess: MMAP
  
  # エンコード値の設定
  graph.encoded_values: road_class, road_environment, max_speed, surface
  
  # プロファイル（車のみでメモリ節約）
  profiles:
    - name: car
      weighting: fastest
      turn_costs: false
  
  # ルーティング設定
  routing:
    max_visited_nodes: 1000000
    ch.disabling_allowed: true

# サーバー設定
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0