graphhopper:
  # OpenStreetMap データファイルのパス
  datareader.file: /graphhopper/data/kanto-latest.osm.pbf
  
  # グラフキャッシュの保存場所
  graph.location: /graphhopper/graph-cache
  
  # カスタムモデルディレクトリ
  custom_models.directory: /graphhopper/custom_models
  
  # インポート設定
  import.osm.ignored_highways: "footway,cycleway,path,pedestrian,steps,track,bridleway,corridor,platform,raceway"
    
  # 標高データを無効化（デモ用）
  graph.elevation.provider: ""
  
  # エンコーディング設定
  graph.encoded_values: car_access, car_average_speed, bike_access, bike_average_speed, foot_access, foot_average_speed, road_class, road_environment, max_speed, surface
  
  # 有効にするプロファイル
  profiles:
    - name: car
      weighting: custom
      custom_model_files: [car_custom.json]
    - name: bike
      weighting: custom
      custom_model_files: [bike_custom.json]
    - name: foot
      weighting: custom
      custom_model_files: [foot_custom.json]
  
  # プロファイルごとのCH (Contraction Hierarchies) 設定
  profiles_ch:
    - profile: car
    - profile: bike
    - profile: foot
  
  # ルーティングの詳細設定
  routing:
    # 最大訪問ノード数
    max_visited_nodes: 1000000

# サーバー設定
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  request_log:
    appenders: []