graphhopper:
  # OpenStreetMap データファイルのパス
  datareader.file: /graphhopper/data/map.osm.pbf
  
  # グラフキャッシュの保存場所
  graph.location: /graphhopper/graph-cache
  
  # カスタムモデルディレクトリ
  custom_models.directory: /graphhopper/custom_models
  
  # インポート設定
  import.osm.ignored_highways: ""
    
  # 標高データを無効化（デモ用）
  graph.elevation.provider: ""
  
  # エンコード値の設定（GraphHopper 9.1用）
  graph.encoded_values: car_access, car_average_speed, bike_access, bike_average_speed, foot_access, foot_average_speed, road_class, road_environment, max_speed, surface
  
  # 有効にするプロファイル（GraphHopper 9.1用）
  profiles:
    - name: car
      weighting: custom
      custom_model_files: [car_custom.json]
    - name: bike
      weighting: custom
      custom_model_files: [bike_custom.json]
    - name: foot
      weighting: custom
      custom_model_files: [foot_custom.json]
  
  # ルーティングの詳細設定
  routing:
    # 最大訪問ノード数
    max_visited_nodes: 1000000

# サーバー設定
server:
  application_connectors:
    - type: http
      port: 8991  # 内部ポートを8991に変更
      bind_host: 127.0.0.1  # localhostのみにバインド
  request_log:
    appenders: []
  # 管理コネクタの設定（ヘルスチェック用）
  admin_connectors:
    - type: http
      port: 8992  # 管理ポートも変更
      bind_host: 127.0.0.1