graphhopper:
  # OpenStreetMap データファイルのパス
  datareader.file: /graphhopper/data/map.osm.pbf
  
  # グラフキャッシュの保存場所
  graph.location: /graphhopper/graph-cache
  
  # インポート設定
  import.osm.ignored_highways: ""
    
  # 標高データを無効化（デモ用）
  graph.elevation.provider: ""
  
  # エンコード値の設定（GraphHopper 9.1用）
  graph.encoded_values: road_class, road_environment, max_speed, surface
  
  # 有効にするプロファイル（GraphHopper 9.1用）
  profiles:
    - name: car
      weighting: custom
      custom_model:
        speed:
          - if: "true"
            limit_to: 130
  
  # ルーティングの詳細設定
  routing:
    # 最大訪問ノード数
    max_visited_nodes: 1000000

# サーバー設定
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  request_log:
    appenders: []