name: Build and Push S3-enabled Docker Images

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1

jobs:
  build-and-push:
    name: Build and Push S3 Version to ECR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push S3-enabled GraphHopper API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: graphhopper-api
        IMAGE_TAG: latest
      run: |
        echo "Building S3-enabled version..."
        docker build -f services/graphhopper/Dockerfile.s3 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "S3-enabled API image pushed: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"